In [3]:
import torch

randint = torch.randint(-100, 100, (6,))

tensor([ 74,  18, -82, -40, -37,  41])

In [4]:
randint

tensor([ 74,  18, -82, -40, -37,  41])

In [5]:
randint.shape

torch.Size([6])

In [6]:
tensor = torch.tensor([[0.1,1.2],[2.2,2.1],[3.1,3.3]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 2.1000],
        [3.1000, 3.3000]])

In [7]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
zeros.shape

torch.Size([2, 3])

In [9]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
input = torch.empty(2,3)

In [11]:
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [14]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [17]:
logspace = torch.logspace(start=-10,end = 10,steps=5)

In [18]:
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [19]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
import torch
import numpy as np
import time 
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [25]:
%%time
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.4f}")

0.0013
CPU times: user 1.02 ms, sys: 1.32 ms, total: 2.34 ms
Wall time: 1.79 ms


In [28]:
# define a probability tensor
probabilities = torch.tensor([0.1,0.9])

samples = torch.multinomial(probabilities,num_samples=10,replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 0, 1, 1, 1])


In [29]:

tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim=0)
print(out)

tensor([1, 2, 3, 4, 5])


In [30]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [31]:
out = torch.triu(torch.ones(5,5))
print(out)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [32]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,float('-inf'))
print(out)

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [33]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [42]:
input = torch.zeros(2, 3, 4)

out = input.transpose(1, 2)
print(out)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [55]:
B = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

In [86]:
torch.transpose(B,0,2)

tensor([[[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]],

        [[ 4, 16],
         [ 8, 20],
         [12, 24]]])

In [87]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1,tensor2,tensor3])

In [88]:
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [89]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 6.9514,  2.3045, -0.0628], grad_fn=<SqueezeBackward4>)


In [91]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0],dtype=torch.float32)

softmax_output = F.softmax(tensor1,dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [96]:
import torch
import torch.nn as nn

# 定义嵌入层
embedding = nn.Embedding(num_embeddings=10, embedding_dim=3)

# 输入是一个索引序列
input_indices = torch.tensor([1, 2, 3, 4])

# 获取嵌入向量
embedded_vectors = embedding(input_indices)

print("输入索引:", input_indices)
print("嵌入向量:\n", embedded_vectors)


输入索引: tensor([1, 2, 3, 4])
嵌入向量:
 tensor([[-0.1143, -0.9531, -0.2806],
        [-0.4763,  0.0446,  0.2086],
        [ 1.4409,  0.5594, -0.8652],
        [ 1.0587, -1.0321, -0.2012]], grad_fn=<EmbeddingBackward0>)


In [101]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[1, 2, 4], [5, 6, 7]])


In [102]:
a.shape

torch.Size([3, 2])

In [103]:
b.shape

torch.Size([2, 3])

In [104]:
a @ b

tensor([[11, 14, 18],
        [23, 30, 40],
        [35, 46, 62]])

In [105]:
print(torch.matmul(a, b))

tensor([[11, 14, 18],
        [23, 30, 40],
        [35, 46, 62]])


In [108]:
with open('ebook_free.text', 'r', encoding='UTF-8') as f:
    text = f.read()
print(len(text))
print(text[:200])  # 打印前200个字符



378436
The Project Gutenberg eBook of Hollyhock House: A Story for Girls

This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no res


In [109]:

chars = sorted(set(text))
print(len(chars))
print(chars)
vocabulary_size = len(chars)  # 词汇表大小


96
['\n', ' ', '!', '#', '$', '%', '&', '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'è', 'é', 'ê', 'ï', 'ô', 'ö', 'ü', '—', '‘', '’', '“', '”', '•', '™']


In [110]:

string_to_int = {ch: i for i, ch in enumerate(chars)}
int_to_string = {i: ch for i, ch in enumerate(chars)}

encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: "".join([int_to_string[i] for i in l])

print(encode("hello"))
print(decode([63, 60, 67, 67, 70]))

# 使用torch处理数据
data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

# 分成训练集 验证集
n = int(0.8 * len(data))
train_data = data[:n]
val_data = data[n:]


[63, 60, 67, 67, 70]
hello
tensor([46, 63, 60,  1, 42, 73, 70, 65, 60, 58, 75,  1, 33, 76, 75, 60, 69, 57,
        60, 73, 62,  1, 60, 28, 70, 70, 66,  1, 70, 61,  1, 34, 70, 67, 67, 80,
        63, 70, 58, 66,  1, 34, 70, 76, 74, 60, 24,  1, 27,  1, 45, 75, 70, 73,
        80,  1, 61, 70, 73,  1, 33, 64, 73, 67, 74,  0,  0, 46, 63, 64, 74,  1,
        60, 57, 70, 70, 66,  1, 64, 74,  1, 61, 70, 73,  1, 75, 63, 60,  1, 76,
        74, 60,  1, 70, 61,  1, 56, 69, 80, 70])


In [112]:

# Block Size（块大小）是指在处理文本时，模型一次读取或生成的最大文本长度。
block_size = 8
# Batch Size（批大小）是指在一次训练迭代中，模型同时处理的样本数。
batch_size = 4



In [113]:

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)
    x = torch.stack([data[i:i + block_size] for i in ix])
    y = torch.stack([data[i + 1:i + block_size + 1] for i in ix])
    return x, y


x, y = get_batch('train')
print('inputs:')
print(x)
print('targets:')
print(y)

tensor([ 23453, 123244,  24702, 186881])
inputs:
tensor([[12,  0,  0, 92, 51, 60, 74, 10],
        [ 1, 57, 60,  1, 70, 69, 67, 80],
        [ 1, 62, 64, 73, 67, 74, 12,  0],
        [70, 70,  1, 68, 70, 59, 60, 74]])
targets:
tensor([[ 0,  0, 92, 51, 60, 74, 10,  1],
        [57, 60,  1, 70, 69, 67, 80,  1],
        [62, 64, 73, 67, 74, 12,  0,  0],
        [70,  1, 68, 70, 59, 60, 74, 75]])


In [114]:
a = torch.rand(2,3,5)
x,y,z = a.shape
a = a.view(x,y,z)
print(a.shape)

torch.Size([2, 3, 5])


In [115]:
a

tensor([[[0.2872, 0.6476, 0.0627, 0.6736, 0.9227],
         [0.6924, 0.4511, 0.6840, 0.8489, 0.9387],
         [0.0170, 0.4308, 0.1955, 0.3529, 0.5058]],

        [[0.0602, 0.3831, 0.0138, 0.2539, 0.6571],
         [0.7560, 0.3171, 0.9134, 0.1071, 0.0292],
         [0.0489, 0.2914, 0.6241, 0.0763, 0.4940]]])

In [116]:
vocabulary_size

96

In [117]:
token_embedding_table = nn.Embedding(vocabulary_size, vocabulary_size)

In [118]:
token_embedding_table

Embedding(96, 96)

In [119]:
context = torch.zeros((1, 1), dtype=torch.long, device=device)

In [120]:
context

tensor([[0]])

In [123]:
logits = token_embedding_table(context)

In [124]:
logits.shape

torch.Size([1, 1, 96])

In [125]:
B, T, C = logits.shape

In [126]:
logits = logits.view(B * T, C)

In [127]:
logits

tensor([[ 1.2129e+00, -1.8040e+00, -1.0681e+00, -1.8593e+00, -1.7124e-01,
          3.1413e-01,  1.7678e+00, -1.1829e+00,  4.9408e-01, -3.5662e-01,
          1.3281e-01,  7.3895e-01,  8.9466e-01, -3.2394e-01, -1.4077e+00,
         -8.2828e-02, -4.9411e-01, -1.0272e+00,  8.6899e-01, -1.6512e+00,
          5.9302e-01, -2.3484e+00,  9.1464e-01, -9.5414e-01,  1.4977e+00,
          3.8915e-01,  1.4248e-01,  8.0909e-01, -2.4848e-01, -1.7961e+00,
         -6.6514e-01, -5.6737e-01,  8.8064e-01, -3.9170e-01, -1.8491e+00,
         -8.6434e-01,  1.1892e+00, -4.2454e-01,  1.0057e+00, -1.7097e+00,
         -1.4949e+00,  1.5845e+00,  7.6576e-01,  1.6731e+00, -1.2468e+00,
          2.9994e-01,  1.7513e+00, -2.0036e-01,  2.0608e+00,  1.0202e-01,
          7.8385e-01, -5.1874e-01,  3.7423e-01, -1.0148e+00, -5.7158e-01,
          6.1547e-01, -1.5781e-01,  5.5050e-01,  8.9360e-01, -1.0568e+00,
         -7.6476e-01,  1.1765e-01,  1.2795e+00,  2.8652e+00, -3.9811e-01,
         -1.4116e-03, -5.3879e-01,  9.

In [128]:
logits.shape

torch.Size([1, 96])

In [130]:
 xb, yb = get_batch('train')

tensor([189937,  44352, 197806, 127114])


In [131]:
xb

tensor([[64, 69, 60, 58, 67, 56, 59,  1],
        [59, 60, 58, 67, 56, 73, 60, 59],
        [59, 60, 73, 10,  1, 39, 56, 73],
        [59,  0, 63, 56, 77, 60,  1, 67]])

In [132]:
yb

tensor([[69, 60, 58, 67, 56, 59,  1, 74],
        [60, 58, 67, 56, 73, 60, 59,  1],
        [60, 73, 10,  1, 39, 56, 73, 80],
        [ 0, 63, 56, 77, 60,  1, 67, 64]])

In [133]:
x = token_embedding_table(xb)

In [135]:
x.shape

torch.Size([4, 8, 96])

In [136]:
y = token_embedding_table(xb)

In [137]:
y.shape

torch.Size([4, 8, 96])

In [138]:
B, T, C = x.shape

In [139]:
x = x.view(B * T, C)

In [141]:
x.shape

torch.Size([32, 96])

In [143]:
y = yb.view(B * T)

In [144]:
y.shape

torch.Size([32])

In [145]:
F.cross_entropy(x, y)

tensor(5.0241, grad_fn=<NllLossBackward0>)